### ISSUE TITLE
attempt at training resulted in tensor shape based error

### ISSUE THREAD

**Issue by santosh-shriyan** [DwightFoster/Pytorch-TecoGAN#2]
I tried training on my own dataset following the same structure as TecoGAN official repo.
I get the below error.

`root@8d938ed861c2:/home/pear/Downloads/Pytorch-TecoGAN-master# python3 main.py --max_epochs 10 --input_video_dir '/home/pear/Downloads/Pytorch-TecoGAN-master/Dataset_short_temp/' 
  0%|                                                                         | 0/10 [00:00<?, ?it/s]/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3454: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3828: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  0%|                                                                         | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 274, in <module>
    output = FRVSR_Train(inputs, targets, args, discriminator_F, generator_F, batch_idx, counter1, counter2, gen_optimizer, tdiscrim_optimizer)
  File "./code/train.py", line 374, in FRVSR_Train
    return TecoGAN(r_inputs, r_targets, discriminator_F, generator_F, args, step, counter1, counter2,
  File "./code/train.py", line 154, in TecoGAN
    T_vel = torch.stack([T_inputs_VPre_batch, T_inputs_V_batch, T_inputs_VNxt_batch], axis=2)
RuntimeError: stack expects each tensor to be equal size, but got [2, 3, 2, 128, 128] at entry 0 and [4, 3, 2, 128, 128] at entry 2
`

I looked through main.py parser parameters and updated my Dataset training and val folder lengths.

`parser = argparse.ArgumentParser()
parser.add_argument('--rand_seed', default=1, type=int, help='random seed')

# Directories
parser.add_argument('--input_dir_LR', default='', nargs="?",
                    help='The directory of the input resolution input data, for inference mode')
parser.add_argument('--input_dir_len', default=-1, type=int,
                    help='length of the input for inference mode, -1 means all')
parser.add_argument('--input_dir_HR', default='', nargs="?",
                    help='The directory of the input resolution input data, for inference mode')
parser.add_argument('--mode', default='train', nargs="?", help='train, or inference')
parser.add_argument('--output_dir', default="output", help='The output directory of the checkpoint')
parser.add_argument('--output_pre', default='', nargs="?", help='The name of the subfolder for the images')
parser.add_argument('--output_name', default='output', nargs="?", help='The pre name of the outputs')
parser.add_argument('--output_ext', default='jpg', nargs="?", help='The format of the output when evaluating')
parser.add_argument('--summary_dir', default="summary", nargs="?", help='The dirctory to output the summary')
parser.add_argument('--videotype', default=".mp4", type=str, help="Video type for inference output")
parser.add_argument('--inferencetype', default="dataset", type=str, help="The type of input to the inference loop. "
                                                                         "Either video or dataset folder.")

# Models
parser.add_argument('--g_checkpoint', default=None,
                    help='If provided, the generator will be restored from the provided checkpoint')
parser.add_argument('--d_checkpoint', default=None, nargs="?",
                    help='If provided, the discriminator will be restored from the provided checkpoint')
# parser.add_argument('--f_checkpoint', default=None, nargs="?",
#                  help='If provided, the fnet will be restored from the provided checkpoint')
parser.add_argument('--num_resblock', type=int, default=16, help='How many residual blocks are there in the generator')
parser.add_argument('--discrim_resblocks', type=int, default=4, help='Number of resblocks in each resnet layer in the '
                                                                     'discriminator')
parser.add_argument('--discrim_channels', type=int, default=128, help='How many channels to use in the last two '
                                                                      'resnet blocks in the discriminator')
# Models for training
parser.add_argument('--pre_trained_model', type=str2bool, default=False,
                    help='If True, the weight of generator will be loaded as an initial point'
                         'If False, continue the training')
parser.add_argument('--vgg_ckpt', default='./model/', help='path to checkpoint file for the vgg19')

# Machine resources
parser.add_argument('--cudaID', default='0', help='CUDA devices')
parser.add_argument('--queue_thread', default=8, type=int,
                    help='The threads of the queue (More threads can speedup the training process.')

# Training details
# The data preparing operation

parser.add_argument('--RNN_N', default=10, nargs="?", help='The number of the rnn recurrent length')
parser.add_argument('--batch_size', default=4, type=int, help='Batch size of the input batch')
parser.add_argument('--flip', default=True, type=str2bool, help='Whether random flip data augmentation is applied')
parser.add_argument('--random_crop', default=True, type=str2bool, help='Whether perform the random crop')
parser.add_argument('--movingFirstFrame', default=True, type=str2bool,
                    help='Whether use constant moving first frame randomly.')
parser.add_argument('--crop_size', default=32, type=int, help='The crop size of the training image')
# Training data settings
parser.add_argument('--input_video_dir', type=str, default="./Dataset_new_temp/",
                    help='The directory of the video input data, for training')
parser.add_argument('--input_video_pre', default='scene', type=str,
                    help='The pre of the directory of the video input data')
parser.add_argument('--str_dir', default=2000, type=int, help='The starting index of the video directory')
parser.add_argument('--end_dir', default=2001, type=int, help='The ending index of the video directory')
parser.add_argument('--end_dir_val', default=2002, type=int,
                    help='The ending index for validation of the video directory')
parser.add_argument('--max_frm', default=119, type=int, help='The ending index of the video directory')
# The loss parameters

parser.add_argument('--vgg_scaling', default=-0.002,
                    type=float, help='The scaling factor for the VGG perceptual loss, disable with negative value')
parser.add_argument('--warp_scaling', default=1.0, type=float, help='The scaling factor for the warp')
parser.add_argument('--pingpang', default=False, type=str2bool, help='use bi-directional recurrent or not')
parser.add_argument('--pp_scaling', default=1.0, type=float,
                    help='factor of pingpang term, only works when pingpang is True')
# Training parameters
parser.add_argument('--EPS', default=1e-12, type=float, help='The eps added to prevent nan')
parser.add_argument('--learning_rate', default=0.0001, type=float, help='The learning rate for the network')
parser.add_argument('--decay_step', default=250, type=int, help='The steps needed to decay the learning rate')
parser.add_argument('--decay_rate', default=0.8, type=float, help='The decay rate of each decay step')
parser.add_argument('--stair', default=False, type=str2bool,
                    help='Whether perform staircase decay. True => decay in discrete interval.')
parser.add_argument('--beta', default=0.9, type=float, help='The beta1 parameter for the Adam optimizer')
parser.add_argument('--adameps', default=1e-8, type=float, help='The eps parameter for the Adam optimizer')
parser.add_argument('--max_epochs', default=10000000, type=int, help='The max epoch for the training')

# Dst parameters
parser.add_argument('--ratio', default=0.01, type=float, help='The ratio between content loss and adversarial loss')
parser.add_argument('--Dt_mergeDs', default=True, type=str2bool, help='Whether only use a merged Discriminator.')
parser.add_argument('--Dt_ratio_0', default=1.0, type=float,
                    help='The starting ratio for the temporal adversarial loss')
parser.add_argument('--Dt_ratio_add', default=0.0, type=float,
                    help='The increasing ratio for the temporal adversarial loss')
parser.add_argument('--Dt_ratio_max', default=1.0, type=float, help='The max ratio for the temporal adversarial loss')
parser.add_argument('--Dbalance', default=0.4, type=float, help='An adaptive balancing for Discriminators')
parser.add_argument('--crop_dt', default=0.75, type=float,
                    help='factor of dt crop')  # dt input size = crop_size*crop_dt
parser.add_argument('--D_LAYERLOSS', default=True, type=str2bool, help='Whether use layer loss from D')

args = parser.parse_args()
os.environ["CUDA_VISIBLE_DEVICES"] = args.cudaID
`

**Comment by dwight-foster** [comment]
Ok I found the error and it seemed to be a basic batch size issue where it wasn't being changed if the batch_size was different. I have now fixed the issue and uploaded the new train.py file so if you want to redownload it it should now work.

**Comment by santosh-shriyan** [comment]
it worked, the training started.
although the output of the trained model was in the form of a  video, is it possible to get a image to image super-resolution?
And thanks for the quick response, really appreciate it.

**Comment by dwight-foster** [comment]
No problem and if you wanted to do image to image super resolution you would have to edit the code a good amount. Currently it can only do video super resolution.

**Comment by santosh-shriyan** [comment]
Is it in the future scope of this repo?
I am asking this because the official repo has a lot of version incompatibility especially owing to new gpu hardware.
This is will also make this a viable replacement for the official repo which is inactive.

**Comment by dwight-foster** [comment]
No the original repo is only for video super resolution as well. There is no image super resolution in that repo as far as I know. The paper is just focused on video. I may add one in the future but for now that is not a focus.

**Comment by santosh-shriyan** [comment]
Actually the original repo has the option of image to image super resolution, I have successfully ran it on a TF-1.8.0-gpu-py3 docker image problem is that 1.8.0 is not compatible with the new rtx 30 series gpus and a successfully trained model on TF-1.15.0-gpu-py3 does not inference due to code incompatibility.

**Comment by dwight-foster** [comment]
Wow you are right I never saw that I will make try and start working on an implementation now. Thank you for the advice.

**Comment by santosh-shriyan** [comment]
great, hopefully once implemented it would help a lot of people understand and implement it.
Should I keep this issue open or close it?

**Comment by dwight-foster** [comment]
Yes I will close it
