### ISSUE TITLE
Can you share the model?

### ISSUE THREAD

**Issue by twmht** [DwightFoster/Pytorch-TecoGAN#3]
Hi,

Can you share the model?

**Comment by dwight-foster** [comment]
Do you mean the weights of the model. Because if so then I sadly no longer have the weights because I had to delete them due to storage issues.

**Comment by twmht** [comment]
:(

**Comment by Poikilos** [comment]
There are pre-trained models downloadable at the https://github.com/skycrapers/TecoGAN-PyTorch if you follow the readme. Your card has to have CUDA compute capability 3.7 or higher though (torch 0.7.1 is the lowest version available on PyPI for Python 3.9) and you should use my PR there so it runs properly (I made the structure of the modules follow Python standards--See my readme changes).
