### ISSUE TITLE
What should be the input size of the video?

### ISSUE THREAD

**Issue by jiteshm17** [DwightFoster/Pytorch-TecoGAN#5]
Hi, thanks for your implementation, I was able to run it.

However, the output size of the video is always 128x128 no matter the input size. I thought this will upscale the video by a factor of 4

I would like to give input as a 480x320 to get an output video of 1920x1080. Is it possible to achieve this, is there anything that I need to change in the code?

**Comment by dwight-foster** [comment]
When you ran the training did you change the crop size parameter? If you didn't it will automatically crop the videos to 32x32 which upscales to 128x128. To be able to do non square images you may have to manually change the crop size in the code because it the parameters always is square.

**Comment by jiteshm17** [comment]
Thanks for your quick reply @dwight-foster 

I found the part of the code for that. It looks like I also need to change the numbers in the model class file right? As it looks like the current values of the model have been assigned tailored to the 32 crop size
